### ISSUE TITLE
埃姆登2 aimudeng_2表情差分缩放不正确

### ISSUE THREAD

**Issue by Cynic158** [Deficuet/AzurLanePaintingAnalysis-Kt#11]
![PixPin_2024-03-27_21-53-31](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/115249055/9d03e132-6e89-41b6-9156-ea9ab85ca2d5)

**Comment by Deficuet** [comment]
![image](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/36525579/e71ae7cb-f989-4581-80d9-c94032ee410b)
当显示这个的时候，请先确认使用的是已经进行过合并操作的立绘。
比如埃姆登这个换装，需要事先合并`aimudeng_2`和`aimudeng_2_rw`，尽管看起来并不需要合并。
已验证行为正常

![屏幕截图 2024-03-27 115909](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/36525579/cb949c60-42de-44e4-aada-dc075f7ee725)

**Comment by Deficuet** [comment]
[beierfasite_4.zip](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/files/14779396/beierfasite_4.zip)
不能直接发文件，只能打包压缩了
