### ISSUE TITLE
部分无需还原的立绘rect缺少特定信息导致无法被选中

### ISSUE THREAD

**Issue by Cynic158** [Deficuet/AzurLanePaintingAnalysis-Kt#13]
[paintingfaceissues.zip](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/files/14804333/paintingfaceissues.zip)

**Comment by Deficuet** [comment]
立绘合并的问题已确认
差分缩放问题除了光辉的原立绘，其他均无法复现
文件发到你邮箱了
