### ISSUE TITLE
新泽西婚纱差分表情在头纱图层之上

### ISSUE THREAD

**Issue by Deficuet** [Deficuet/AzurLanePaintingAnalysis-Kt#14]
正常图层顺序应该是楼梯-人像-差分表情-头纱婚纱
在当前设计下可能是无法解决的问题

**Comment by Cynic158** [comment]
毕竟现在是直接导入立绘当基本图然后加表情，新泽西这个目前只能通过ps把头纱弄成空png，然后合并成group，自行通过ps用group当底图，然后添加并校准表情，最后在将正常头纱图层放到最顶上来达到效果
