### ISSUE TITLE
表情差分assetbundle提示不会自动复原

### ISSUE THREAD

**Issue by Cynic158** [Deficuet/AzurLanePaintingAnalysis-Kt#15]
在表情差分处，误导入错误的文件后会提示assetbundle不可用，这是正常的，但后续导入正确可用的文件后，并不会自动消除assetbundle不可用这个提示。

所有的表情差分我已经遍历过，剩余可能有问题的如下：
缩放异常相关（缩放异常因人而异）：
光辉1
黑太子2
凌波6
凌波7
龙骧3
企业4
圣地亚哥改
wudao4
信浓4
吸血鬼4

报错异常相关：
火奴鲁鲁5
克利夫兰4
可畏2
利托里奥2
谢菲尔德3

新泽西h需要手动拼接图层
德文郡2并没有问题，但是原表情差分文件较大，说是立绘差分更合适

**Comment by Deficuet** [comment]
关于缩放异常：
除了光辉1和信浓4确认，以及企业4实际是报错以外，其他缩放异常全都复现不了
