### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by shenchang233** [Deficuet/AzurLanePaintingAnalysis-Kt#16]
电脑小白请教以下为什么旧版本显示不可用，新版本直接报错。
![QQ图片20240521165946](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/104640334/87caf505-8d41-4992-9580-adc62d006190)
![QQ图片20240521170018](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/104640334/84c20788-5af1-4e4e-abe6-993f7dbeb2dd)

**Comment by shenchang233** [comment]
已解决，因缺少dependencies文件所致。

**Comment by Deficuet** [comment]
问题解决了？

**Comment by SunRelease** [comment]
> 问题解决了？

大佬，未解决，也出现了缺少dependencies文件同样问题，不知道这个dependencies是java版本（我的是17.0.11）不匹配问题，还是碧蓝立绘的dependencies文件问题。
![image](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/46837438/11c3c1b4-884a-4a76-818e-625e536b9f40)

**Comment by SunRelease** [comment]
已解决，确实是碧蓝的dependencies文件我忘记复制替换新版本了，感谢
