### ISSUE TITLE
无法加载立绘

### ISSUE THREAD

**Issue by MiunaQwQ** [Deficuet/AzurLanePaintingAnalysis-Kt#18]
导入任意painting目录下的非_tex为尾缀的文件时无法加载立绘但能加载表情差分

块“分析文件”的依赖项显示为蓝色，应该是加载成功
块“导入图像”的$face$显示为蓝，其余显示为红，前者应该加载成功，后者则未成功加载（右侧标签页仅有“总体预览”和“$face

保存图片压缩等级：7
自动导入：√立绘 √差分表情文件
立绘根目录：F:\AssetBundles\painting
差分表情根目录：F:\AssetBundles\paintingface
素材文件根目录：F:\AssetBundles

程序版本：v1.0.2
Java版本：jdk-22_windows-x64_bin
Windows版本：Windows 11 Pro for Workstations 24H2 26120.961

![60128352-0dee-45f2-b85c-9d8b3fe6e58a](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/84217789/4353a5fc-eadb-4459-a99b-2f74dd6471d0)
![c898b627908b125272a0ab9a09127d49](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/84217789/e767f76c-344d-4b3f-a6a2-d061a47a8594)

**Comment by Deficuet** [comment]
`立绘根目录`应该指向存放各个部分的`立绘图片`的文件夹，而不是`AssetBundles`

**Comment by Deficuet** [comment]
是各个部分的png图像，例如马耶布雷泽的：
![image](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/36525579/4bb06beb-62b5-4e71-81e3-1f9c199e0eec)

**Comment by Deficuet** [comment]
有很多拼接立绘工具，GitHub里搜索碧蓝航线就能找到不少，这里就不做推荐了
