### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by shangmolichou** [Deficuet/AzurLanePaintingAnalysis-Kt#22]
java.lang.IllegalArgumentException: parameter "file" must be a file。出现这个问题如何解决，是指的哪个file？

**Comment by Deficuet** [comment]
导入的必须是文件而不是文件夹，现在也还没支持硬链接

**Comment by shangmolichou** [comment]
解决了，太久没使用这个工具了，仔细阅读了一遍操作发现把素材根目录搞错了
