### ISSUE TITLE
无法合并

### ISSUE THREAD

**Issue by ysl0148** [Deficuet/AzurLanePaintingAnalysis-Kt#3]
在不缺少依赖的情况下，始终提示无需合并
![image](https://user-images.githubusercontent.com/109747995/230828813-9f1acac8-113e-4f0b-a4fa-633b75f2100b.png)

**Comment by Deficuet** [comment]
那就是不需要合并，一张图就是一个完整的立绘，而不是类似人和舰装等各部分分别在多张图上的情况

**Comment by ysl0148** [comment]
但是我想将新的立绘替换掉旧的立绘无法做到吗？

**Comment by Deficuet** [comment]
对素材文件进行修改吗？做不到，不是拿来干这个的

**Comment by ysl0148** [comment]
但是提取出来的文件本身就是不需要合并的，如果只导入不带tex的文件又会报错，那又怎么使用它才能合成一个新的立绘

**Comment by Deficuet** [comment]
合成一个新的立绘是指什么？这个工具是用来辅助获得完整立绘的，使用前提是你手上已经有还原好的立绘的png图像。无需合并的意思是还原完了立绘并没有被拆成多部分。拿马耶布雷泽原皮举例，她的完整立绘被拆成了四个部分，还原的立绘有四张，可以用这个工具把四张拼一块获得完整的立绘。这个工具没有从素材文件里还原立绘的功能，更没办法无中生有。像你这里举例的22的立绘，它还原完了就是一张完整的22立绘，当然无需进一步处理。

**Comment by ysl0148** [comment]
我懂了，有的立绘分为背景，人物，他的作用就是把背景和人物两个立绘合成一个是吧？

**Comment by Deficuet** [comment]
正确的，而且通常各部分缩放比例都不一样不能单纯靠ps等人工拼合

**Comment by ysl0148** [comment]
感谢感谢
