### ISSUE TITLE
java错误

### ISSUE THREAD

**Issue by Sky076** [Deficuet/AzurLanePaintingAnalysis-Kt#6]
![image](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/97520054/114bc1ac-4347-485a-b560-97439b77bb92)
如图，使用jre1.8，已配置环境变量，已尝试使用管理员权限运行

**Comment by Deficuet** [comment]
尝试使用Java 11。readme有写

**Comment by Sky076** [comment]
问题解决了，环境变量里最新版本的java顺序在上面，导致总是报错
