### ISSUE TITLE
水星纪念meta立绘读取失败

### ISSUE THREAD

**Issue by yuelengqingchen** [Deficuet/AzurLanePaintingAnalysis-Kt#7]
![image](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/14126590/dad7386d-9ef8-4f1e-84b2-9b4666d72c32)
![image](https://github.com/Deficuet/AzurLanePaintingAnalysis-Kt/assets/14126590/ce2daaf5-52e3-4456-869f-b92b0d2921dc)

**Comment by Deficuet** [comment]
尝试使用最新版本，见Releases

**Comment by yuelengqingchen** [comment]
@好了，之前试过最新版是覆盖旧版本的，刚才删除旧版本重新试了下可以了

> 尝试使用最新版本，见Releases
